#
# ${project.name} - v${project.version}
# Developed by https://codeitforyou.com/
#

settings:
  general:
    # Enabling this will skip votes where the user
    # currently isn't online.
    onlineonly: true

  # This is where the data will be stored.
  storage:
    # Types: SQLITE, MYSQL and MONGODB.
    type: 'SQLITE'
    host: 'localhost'
    username: '${project.name}'
    password: ''
    port: 3306
    database: '${project.name}_db'
    prefix: ''

rewards:
  '50votes':
    requirements:
      test:
        requirement-type: 'EXPRESSION'
        expression: '%cifyvotes_votes% == 50'
    actions:
      - '[MESSAGE] &b[Votes] &7You voted &f50 times &7and received a &bDiamond Sword&7!'
  '25votes':
    requirements:
      test:
        requirement-type: 'EXPRESSION'
        expression: '%cifyvotes_votes% == 25'
    actions:
      - '[MESSAGE] &b[Votes] &7You voted &f25 times &7and received a &fIron Sword&7!'
  'donor':
    requirements:
      test:
        requirement-type: 'HAS_PERMISSION'
        input: 'cifyvotes.donor'
    actions:
      - '[MESSAGE] &b[Votes] &7You voted as a &ddonator &7and received a &aEmerald Sword&7!'
  '1in10':
    requirements:
      test:
        requirement-type: 'HAS_CHANCE'
        chance: 10 # 1/10 chance
    actions:
      - '[MESSAGE] &b[Votes] &7You got lucky (&b1/10&7) and received a diamond&7!'